name: 'Kiuwan Baseline Analysis'
author: 'Kiuwan'
description: 'Run Kiuwan Baseline analysis on the repository executing the action'
inputs:
  kiuwanbaseurl:
    description: 'Base URL of the kiuwan server. Empty to go to kiuwan.com SaaS version. Example: https://myserver.com'
    required: false
    default: 'https://www.kiuwan.com'
  project:
    description: 'Name of Kiuwan project'
    required: false
    default: ${{ github.repository }}
  label:
    description: 'Label of the analysis'
    required: false
    default: ${{ github.run_number }}
  userid:
    description: 'Username for kiuwan platform'
    required: true
  password:
    description: 'Password for kiuwan platform'
    required: true
  databasetype:
    description: 'Database type files in the project, if any. Can be one or more of [none, transacsql, plsql, informix]'
    required: false
    default: 'none'
  advancedparams:
    description: 'Rest of parameters to use in the Kiuwan Local Analyzer. Please review documentation to see format at https://www.kiuwan.com/docs/display/K5/Kiuwan+Local+Analyzer+CLI+-+Command+Line+Interface'
    required: false
    default: ''

outputs:
  result:
    description: 'Return code of the execution of kiuwan'
  analysisurl:
    description: 'URL of the executed analysis'

branding:
  color: 'green'
  icon: 'code'

runs:
  using: 'docker'
  image: 'Dockerfile'
